spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 2ms
      quiet-period: 1ms  # Ensure quiet-period is greater than poll-interval
    livereload:
      enabled: true

logging:
  level:
    org.springframework.boot.devtools: TRACE
